### PR TITLE
fix: allow space at docstring parse

### LINKED ISSUE #47: Allow space inside argument defenition
https://github.com/tilt-dev/starlark-lsp/blob/49955f646631551720ef540e4bac9c47f7ad16be/pkg/docstring/docstring.go#L391

[starlark-lsp](https://github.com/tilt-dev/starlark-lsp) use `LUCI` docstring parser. Wheile parse an arg line, it doesn't allow any space inside argument, though it might be useful for add some type defenitions.

Examples:
image

We could revised it into `^(\S.*?)\s*:\s*(.*)$`, then could support more flexible argument defenition.

image

### PR DESCRIPTION
**Pull request by cutecutecat**
close #47 

Signed-off-by: cutecutecat <starkind1997@gmail.com>

### CODE REVIEW

File: pkg/docstring/docstring.go [hunk 1]
```diff
@@ -388,7 +388,10 @@ func parseBlockTitle(l string) (title string, ok bool) {
 }
 
 // fieldRe matches "field: ...".
-var fieldRe = regexp.MustCompile(`^(\S*)\s*:\s*(.*)$`)
+//
+// fix: Modify `^(\S*)\s*:\s*(.*)$` to `^(\S.*?)\s*:\s*(.*)$` will allow spaces,
+// and accept lines like `os (str): name of os`
```
Comment (nicksieger) [inline pkg/docstring/docstring.go:393]: Can you change this to simply document how the regex works? Something like
```suggestion
// fieldRe matches arguments in docstrings, allowing spaces around the name and type
```

Comment (cutecutecat) [reply pkg/docstring/docstring.go]: Fine. Thank you for review.

**Review by nicksieger — APPROVED** [review]

**Comment by nicksieger** [comment]
Thanks!
